/*
 * Student Name: Michael Bonnet
 * Assignment: hw02
 * Class Name: CSE 1320 Intermediate Programming
 * Class Section: 
 * Class Instructor: Bud Davis
 */

#include <stdio.h>
#include <assert.h>
#define __USE_MISC
#include <math.h>

/*
 * Program with code, comments, and whitespace :
 * Program with code and comments              :
 * Program with code and whitespace            :
 * Program with just code                      :
 *
*/

// This global variable is an array of type float with a size of 360 indexes to store float terms.
// The purpose of this global variable is to store the result of a Taylor Series (4 terms) for each integer value >= 0 and < 360.
float lookup_table[360] = {};

// This function takes a float input representing a quantity of degrees,
// then performs input validation to ensure the quantity of degrees is >= 0.0 and < 360.0.
// The function then calculates and returns the sine of the input degree quantity
// using a Taylor Series (technically a Maclaurin series, hence the function name) to the 4th term.
float maclaurin_sine(float input_angle)
{
	int i;
	float x, sum=0, term, numerator, denominator;

	// assert( input_angle >= 0.0 );
	// assert( input_angle < 360.0 );

	if (input_angle >= 0.0 && input_angle < 360.0)
	{
		x = input_angle * (M_PI/180);
		numerator = x;
		denominator = 1;
		i = 2;

		do
		{
			term = numerator / denominator;
			numerator = -numerator * x * x;
			denominator = denominator * i * (i+1);
			sum = sum + term;
		} while (fabs(term)>= 0.00001);

		return sum;
	}
			else
			{
				return 0.0;
			}
} // END OF FUNCTION maclaurin_sine()

// This function populates the global variable lookup table with the results of the Taylor Series.
void init(void)
{
	// This assert statement
	assert(sizeof(lookup_table == 360));
	// This for loop iterates through all integers i in the domain(x) = (0 =< x < 360),
	// getting the result of the taylor series for that i value (cast to float),
	// and storing it in the corresponding index of the lookup table.
	for(int i = 0; i < 360; i++)
	{
 		lookup_table[i] = maclaurin_sine((float)i); // if unclear, (float)i casts the integer value of i to float,
 		                                            // in order for it to be in acceptable type for input into the function maclaurin_sine,
 		                                            // which requires a float input.
	}
} // END OF FUNCTION init()

// This function uses linear interpolation (using the values in the lookup table generated by maclaurin_sine) to return a more accurate value for sin.
float sin_(float input_angle)
{
	// do this shit right here
	// does the whole linear interpolation thing 
}

// This function determines the error, or the difference between 
// the correct result (the result of using sin(x), the accurate math.h fuction)
// and the incorrect result (the result of using sin_(x), the somewhat inaccurate linear interpolation function)
float error_(float input_angle)
{
	// Error = Correct - Measured
	// Correct = sin(input_angle)
	// Measured = sin_(input_angle)
	float error = sin(input_angle) - sin_(input_angle);

	return error;
}


// This is the main function that executes all the other functions to produce desired output.
int main (void)
{
	// Population of lookup table.
	init();

	float input_angle;
	printf("Enter an angle: \n");
	scanf("%f", &input_angle);

	printf("%f %f %f %f", input_angle, sin(input_angle), sin_(input_angle), error_(input_angle));

	return 0;
}

// I used these print statements to test if the lookup table properly populated in the function init().

// printf("Value of (lookup_table) maclaurin_sine(0):   %f", lookup_table[0]);
// printf("Value of maclaurin_sine(0):   %f", maclaurin_sine[0]);
// printf("Value of (lookup_table) maclaurin_sine(17):  %f", lookup_table[17]);
// printf("Value of maclaurin_sine(17):   %f", maclaurin_sine[17]);
// printf("Value of (lookup_table) maclaurin_sine(30):  %f", lookup_table[30]);
// printf("Value of maclaurin_sine(30):   %f", maclaurin_sine[30]);
// printf("Value of (lookup_table) maclaurin_sine(60):  %f", lookup_table[60]);
// printf("Value of maclaurin_sine(60):   %f", maclaurin_sine[60]);
// printf("Value of (lookup_table) maclaurin_sine(90):  %f", lookup_table[90]);
// printf("Value of maclaurin_sine(90):   %f", maclaurin_sine[90]);
// printf("Value of (lookup_table) maclaurin_sine(120): %f", lookup_table[120]);
// printf("Value of maclaurin_sine(120):   %f", maclaurin_sine[120]);
// printf("Value of (lookup_table) maclaurin_sine(134): %f", lookup_table[134]);
// printf("Value of maclaurin_sine(134):   %f", maclaurin_sine[134]);
// printf("Value of (lookup_table) maclaurin_sine(150): %f", lookup_table[150]);
// printf("Value of maclaurin_sine(150):   %f", maclaurin_sine[150]);
// printf("Value of (lookup_table) maclaurin_sine(180): %f", lookup_table[180]);
// printf("Value of maclaurin_sine(180):   %f", maclaurin_sine[180]);
// printf("Value of (lookup_table) maclaurin_sine(270): %f", lookup_table[270]);
// printf("Value of maclaurin_sine(270):   %f", maclaurin_sine[270]);
// printf("Value of (lookup_table) maclaurin_sine(359): %f", lookup_table[359]);
// printf("Value of maclaurin_sine(359):   %f", maclaurin_sine[359]);

