# Name of Last Editor : Michael Bonnet
# Date of Last Edit   : 04/30/2019
# Time of Last Edit   : 17:14 Central Daylight Time (GMT-6)

CFLAGS = -Wall -g -O0 -std=c99
CC=gcc

all: hw8

hw8: hw8_Bonnet_Michael.c
	${CC} ${CFLAGS} hw8_Bonnet_Michael.c